name: Vaibhav Dhiman
avatar: images/profile.png # Avatar image. Default to "images/profile.webp".
bio: 'Pythonist.'
company: <a href="https://instaplot-fire.web.app" target="_blank">Instaplot</a> # HTML markup are supported, such as: <a href="https://example.com" target="_blank" rel="noopener noreferrer">Company</a>.
location: India # HTML markup are supported, such as: <a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>.
# about: https://razonyang.com # The external about page. The internal about page will be used if not set.
params: {
  # layout: compact
}
social:
  email: vaibhavdhi@proton.me
  github: VaibhavSys/VaibhavSys.github.io
