baseURL: /
title: Vaibhav - Software Developer
theme: hugo-theme-bootstrap
copyright: 'Copyright © 2022-{year} Vaibhav Dhiman. All Rights Reserved.'
defaultContentLanguage: en
disableLanguages:
 - fr
 - zh-cn
 - zh-tw
paginate: 10
# paginatePath: page
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

blackfriday:
  hrefTargetBlank: true

taxonomies:
  category: categories
  series: series
  tag: tags
  authors: authors

build:
  writeStats: true

permalinks:
  news: /news/:year/:month/:title/
